  db:
    image: mysql:latest
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT = 3306
      - DATABASE_USER = admin
      - DATABASE_PASSWORD = admin
      - DATABASE_NAME = integradora2
    ports:
      - 3306:3306
    volumes:
      - my-db-volume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - 3000:3000
    depends_on:
      - db

